home/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('category/', views.category, name='category'),
    path('products/<str:id>/<slug:slug>', views.prod_list, name='prod_list'),
    path('products-details/<str:id>/<slug:slug>', views.prod_detail, name='prod_detail'),
]

order/urls.py
from django.urls import path
from . import views

app_name= 'order'

urlpatterns = [
    path('order/', views.order, name='order'),
    path('addtoshopcart/', views.addtoshopcart, name='addtoshopcart'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('updatequantity/', views.updatequantity, name='updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('ordercompleted/', views.ordercompleted, name='ordercompleted'),
]

shopa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as UserViews

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('login/', UserViews.loginform, name='loginform'),
    path('logout/', UserViews.logoutfunc, name='logoutfunc'),
    path('register/', UserViews.registerform, name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('update/', UserViews.userupdate, name='imageupdate'),
    path('password/', UserViews.userpassword, name='userpassword'),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

from django.forms import Textarea, TextInput
from django.forms import ModelForm
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Profile(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    title = models.CharField(max_length=100)
    keywords= models.CharField(max_length=225)
    description = models.CharField(max_length=225, null=True)
    company = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=300)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50, blank=True)
    icon = models.ImageField(blank=True, null=True, upload_to='images/')
    logo = models.ImageField(blank=True, null=True, upload_to='images/')
    cart_icon = models.ImageField(blank=True, null=True, upload_to='images/')
    menu_icon = models.ImageField(blank=True, null=True, upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    about = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    bannertext= models.CharField(max_length=300)

    def __str__ (self):
        return self.title


class Manufacturers(models.Model):
    title = models.CharField(max_length=10, blank=True, null=True)
    manufacturers = models.ImageField(blank=True, null=True, upload_to='images/')

    def __str__(self):
        return self.title
     


class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Pending', 'Pending'),
        ('Closed', 'Closed'),
    )

    first_name = models.CharField(blank=True, max_length=20)
    last_name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.TextField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name
    
class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['first_name', 'last_name', 'email', 'subject', 'message']

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core import paginator
from django.http import HttpResponse
from .models import *
from product.models import *
from user.models import *
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.
def index(request):
    profile = Profile.objects.get(pk=1)
    manufacturers = Manufacturers.objects.all()
    category = Category.objects.all()[:9]
    category_a = Category.objects.all()[:4]
    new_prod= Product.objects.filter(new_prod=True)[:6]
    carousel_a=Carousel_a.objects.get(pk=1)
    carousel_b=Carousel_b.objects.get(pk=1)
    carousel_c=Carousel_c.objects.get(pk=1)
    carousel_d=Carousel_d.objects.get(pk=1)
    featured=Product.objects.filter(featured=True)[:6]
    new_prod_slide=Product.objects.filter(new_prod_slide=True)[:4]
    new_prod_slidea=Product.objects.filter(new_prod_slidea=True)[:4]
    popular=Product.objects.filter(popular=True)[:6]
    upcoming=Product.objects.filter(upcoming=True)[:10]
    bestselling=Product.objects.filter(bestselling=True)[:6]
    # profiles = UserProfile.objects.get(user__username = request.user.username) 
    

    context = {
        'profile': profile,
        # 'profiles': profiles,
        'manufacturers': manufacturers,
        'category': category,
        'category_a': category_a,
        'new_prod': new_prod,
        'carousel_a': carousel_a,
        'carousel_b': carousel_b,
        'carousel_c': carousel_c,
        'carousel_d': carousel_d,
        'featured': featured,
        'popular':popular,
        'upcoming': upcoming,
        'new_prod_slide':new_prod_slide,
        'new_prod_slidea': new_prod_slidea,
        'bestselling': bestselling,
        
    }


    
    return render(request, 'index.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your Message has been sent! Our Customer Service Team will reach you soon")
            return redirect('/contact')

    profile = Profile.objects.get(pk=1)
    form = ContactForm
    manufacturers = Manufacturers.objects.all()
    # profiles = UserProfile.objects.get(user__username = request.user.username)

    context = {
        'profile': profile,
        'form': form,
        'manufacturers': manufacturers,
        # 'profiles': profiles,
    }


    return render(request,'contact.html', context)


def category(request):
    profile=Profile.objects.get(pk=1)
    # profiles = UserProfile.objects.get(user__username = request.user.username) 
    manufacturers= Manufacturers.objects.all()
    category = Category.objects.order_by('-created_at').filter(status=True)
    category_a = Category.objects.all()[:4]
    paginator = Paginator(category, 8)
    page = request.GET.get('page')
    paged_category = paginator.get_page(page)

    context = {
        'profile': profile,
        # 'profiles': profiles,
        'manufacturers': manufacturers,
        'category': paged_category,
        'category_a': category_a,
    }


    return render(request, 'category.html', context)


def prod_list(request,id,slug):
    profile=Profile.objects.get(pk=1)
    category=Category.objects.all()
    category_a = Category.objects.all()[:4]
    product=Product.objects.filter(category_id=id)
    # products=Product.objects.get(pk=id)
    manufacturers=Manufacturers.objects.all()
    # profiles = UserProfile.objects.get(user__username = request.user.username) 

    context = {
        'profile': profile,
        # 'profiles': profiles,
        'category': category,
        'product': product,
        # 'products': products,
        'manufacturers': manufacturers,
        'category_a': category_a,
    }

    return render(request, 'prod-list.html', context)

def prod_detail(request,id,slug):
    profile=Profile.objects.get(pk=1)
    category=Category.objects.all()
    category_a = Category.objects.all()[:4]
    product=Product.objects.filter(category_id=id)
    products=Product.objects.get(pk=id)
    manufacturers=Manufacturers.objects.all()
    images = Images.objects.filter(product_id=id)
    # profiles = UserProfile.objects.get(user__username = request.user.username) 

    context = {
        'profile': profile,
        # 'profiles': profiles,
        'category': category,
        'product': product,
        'products': products,
        'manufacturers': manufacturers,
        'category_a': category_a,
        'images': images,
    }
    return render(request, 'prod-details.html', context)

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="{{profile.icon.url}}" type="images/gif">
    <link rel="stylesheet" href="{% static '' %}css/main.css">
    <link rel="stylesheet" href="{% static '' %}css/responsiveness.css">
    <style>
        .resres textarea{
            border-radius: 10px;
            outline: none;
            border: 1px solid gray;
            padding-left: 5px;
            padding-top: 5px;
            padding-bottom: 5px;
            font-size: 12px;
            width: 96%;
        }
        .resres textarea:focus{
            border-radius: 10px;
            outline: none;
            border: 1px solid orangered;
            padding-left: 5px;
            padding-top: 5px;
            padding-bottom: 5px;
            font-size: 12px;
        }
    </style>
    <title>Home</title>
</head>
<body>
    <section>
        {% block ghead %}{% endblock ghead %}
        <div class="container-fluid">
            {% block header %}{% endblock header %}
            {% block content %}{% endblock content %}
        </div>
        <div class="container-fluid copyfoot1">
            {% block copyfoot %}{% endblock copyfoot %}
        </div>
    </section>




<script src="{% static '' %}js/smooth-scroll.js.js"></script>
<script>
	var scroll = new SmoothScroll('a[href*="#"]');
</script>



<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

home/templates/ghead.html
<div class="container-fluid top" id="top">
    <div class="icon">
        <div class="social">
            <i class="fa fa-twitter" aria-hidden="true"></i>
        </div>
        <div class="social">
            <i class="fa fa-facebook" aria-hidden="true"></i>
        </div>
        <div class="social">
            <i class="fa fa-youtube" aria-hidden="true"></i>
        </div>
        <div class="social">
            <i class="fa fa-tumblr" aria-hidden="true"></i>
        </div>
    </div>
    <a href="{% url 'index' %}" class="active"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
    
    {% if user.id is not None %}
        <a href="{% url 'user' %}"><i class="fa fa-user" aria-hidden="true"></i>Welcome! 
                                {% if request.user.first_name %}
                                    {{request.user.first_name}}
                                {% else %}
                                    {{request.user.username}}
                                {% endif %}
        </a>
        <a href="{% url 'order:shopcart' %}"><i class="fa fa-cart-plus" aria-hidden="true"></i>
            
            {% if itemcount > 0 %}
                {{itemcount}}
            {% else %}
                0
            {% endif %}
                 Item(s)
        </a>
        <a href="{% url 'logoutfunc' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
        <a href="{% url 'contact' %}"><i class="fa fa-envelope" aria-hidden="true"></i>Contact us</a>
        <a href=""><i class="fa fa-info-circle" aria-hidden="true"></i>About Us</a>
    {% else %}
        <a href="{% url 'loginform' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
        <a href="{% url 'registerform' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Free Register</a>
        <a href="{% url 'contact' %}"><i class="fa fa-envelope" aria-hidden="true"></i>Contact us</a>
        <a href=""><i class="fa fa-info-circle" aria-hidden="true"></i>About Us</a>
    {% endif %}
        
    
    <!-- {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-{{message.tags}}" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{message}}
            </div>
        {% endfor %}
    {% endif %} -->
</div>

home/templates/header.html
{% load static %}
<div class="container c1">
    <div class="logo">
        <div class="ham">
                    <!-- HAMBURGER -->
            <div class="menu-wrap">
                <input type="checkbox"  class="toggler">
                <div class="hamburger"><div></div></div>
                <div class="menu-list">
                    <div>
                        <div>
                            <ul>
                                <li><a href="{%url 'index' %}">Home</a></li>
                                <li><a href="">About us</a></li>
                                <li><a href="{% url 'contact' %}">Contact us</a></li>
                                
                                {% if user.id is not None %}
                                    <li class="catr"><span style="color: orangered; font-weight:bold">OUR CATEGORIES</span> <a href="{% url 'category' %}">See all</a></li>
                                
                                    {% if category_a %}
                                        {% for items in category_a  %}
                                            <li><a href="{% url 'prod_list' items.id items.slug %}">{{items.title}}</a></li>
                                        {% endfor %}
                                    {% endif %}
                                  
                                    <li class="catr"><span style="color: orangered; font-weight:bold">MY ACCOUNT</li>
                                    <li><a href="{% url 'user' %}">Account Info</a></li>
                                    <li><a href="{% url 'logoutfunc' %}">Logout</a></li>
                                {% else %}
                                    <li class="catr"><span style="color: orangered; font-weight:bold">MY ACCOUNT</li>
                                    <li><a href="{% url 'registerform' %}">Register</a></li>
                                    <li><a href="{% url 'loginform' %}">Login</a></li>
                                {% endif %}
                                    
                            </ul>
                        </div>
                    </div>
                </div> 
                
                <!-- {% if messages %}
                    {% for message in messages  %}
                        <div class="alert alert-success alert-{{message.tags}}" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %} -->
                    
            </div>
            <img src="{% static '' %}images/SHOPCART.png" alt="">
        </div>
        <div class="smallacc">
            <a href="{% url 'user' %}"><i class="fa fa-user" style="position:relative; bottom:6px; color:orange" aria-hidden="true"></i></a>
            
            <a href="{% url 'order:shopcart' %}">
                <i class="fa fa-shopping-cart fe" aria-hidden="true"></i>
                <div class="cart-count">
                    {% if itemcount > 0 %}
                        <span>{{itemcount}}</span>
                    {% else %}
                        <span>0</span>
                    {% endif %}
                </div>
            </a>
        </div>
    </div>
    <div class="line">
        <div class="dot">
            <span>{{profile.bannertext | safe}}</span>
        </div>
        <!-- <div class="sci">
            <i class="fa fa-scissors" aria-hidden="true"></i>
        </div> -->
    </div>
    <div class="euro">
        <br>
        <span class="support" style="margin-top: 10px;">{{profile.contact|safe}}</span>
        <span class="gr">Call charges may apply.</span>
    </div>
</div>

home/templates/prod-details.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block ghead %}{% include 'ghead.html' %}{% endblock ghead %}
<div class="container-fluid">
    {% block header %}{% include 'header.html' %}{% endblock header %}
    {% block content %}
    <div class="container cpd">
        <div class="catgo">
            <h6>Product Details</h6>
        </div>
    </div>
    <div class="container spd">
        <div class="row">
            <div class="col-lg-3 topres">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product">
                            
                            {% if category %}
                                {% for items in category  %}
                                    <div class="pro">
                                        <span><a href="{% url 'prod_list' items.id items.slug %}" style="color: black;""><i class="fa fa-chevron-right" aria-hidden="true"></i>{{items.title}}</a></span>
                                    </div>
                                {% endfor %}
                            {% endif %}
                                
                            
                            <div class="pro">
                                <span><i class="fa fa-chevron-right" aria-hidden="true"></i>See all Categories</span>
                            </div>
                         </div>
                         
                    </div>
                </div>
                <div class="row stili" >
                    <div class="col-lg-12 disca">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="dro">
                                    <h5>50% Discount</h5>
                                    <span>Only Valid for online order</span> <br>
                                    <button>Click here</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="upcoming">
                                    <p style="font-size: 15px; font-weight:bold;">Upcoming Products</p>
                                    <p>Click to view</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="paypal">
                            <div>
                                <img src="{% static '' %}images/paypal.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="pd-hold">
                            <div class="pdv">
                                <span><a href="{% url 'index' %}">Home </a> / </span>
                               <span><a href="{% url 'category' %}">View all Categories </a> / </span>
                               <span>Preview</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product1" style="margin-top: 20px;">
                            <div class="row pete">
                                <div class="col-lg-5">
                                    <div class="carousel slide" id="semo" data-ride="carousel">
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <img src="{{products.image.url}}" alt="">
                                            </div>
                                            
                                            {% if images %}
                                                {% for items in images  %}
                                                <div class="carousel-item">
                                                    <img src="{{items.image.url}}" alt="">
                                                </div>
                                                {% endfor %}
                                            {% endif %}
                                                
                                            
                                             
                                            <a href="#semo" class="carousel-control-prev" data-slide="prev">
                                                <span><i class="fa fa-chevron-left fa-4x" aria-hidden="true" style="color: orange;"></i></span>
                                                
                                            </a>
                                
                                            <a href="#semo" class="carousel-control-next" data-slide="next">
                                                <span><i class="fa fa-chevron-right fa-4x" aria-hidden="true" style="color: orange;"></i></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-7">
                                    <div class="namo">
                                        <h5>
                                            {{products.title}}: 

                                            
                                            {% if products.discount_price %}
                                                <del>&#8358; {{products.price | floatformat:2 | intcomma}}</del>
                                                <span>&#8358; {{products.discount_price| floatformat:2 | intcomma}}</span>
                                            {% else %}
                                                <span>&#8358; {{products.price| floatformat:2 | intcomma}}</span>
                                            {% endif %}
                                                
                                        </h5>
                                        <hr>
                                        <form action="{% url 'order:addtoshopcart' %}" method="POST">
                                        {% csrf_token %}
                                            <div class="namput">
                                                <span>Quantity</span>
                                                <input type="number" name="quantity" placeholder="Qty" value="1" min="{{products.minquantity}}" max="{{products.quantity_instock"> 
                                            </div>
                                            <div class="namp">
                                                <span>Color:</span>
                                                <select name="color" id="" style="width: 30%;">
                                                    <option value="Red">Red</option>
                                                    <option value="Blue">Blue</option>
                                                    <option value="Black">Black</option>
                                                </select>
                                            </div>
                                            <h5 style="margin-bottom: 10px;">{{products.quantity_instock}} Items in stock</h5>
                                            <button type="submit"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Add to Cart</button>
                                            <input type="hidden" name="prodid" value="{{products.id}}">
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-lg-12">
                                    <nav class="nav sete">
                                        <a href="#details" class="nav-link active" data-toggle="tab">Product Details</a>
                                    </nav>
                                    <div class="tab-content csw">
                                        <div class="tab-pane active" id="details">
                                            <div class="hodl">
                                                <h6>Product Information</h6>
                                                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Inventore aliquam, 
                                                    adipisci nemo omnis hic ut tempora perferendis, doloribus doloremque laboriosam, 
                                                    reprehenderit vero. Consectetur recusandae consequatur deserunt eum nisi ipsam aspernatur provident, cupiditate est ducimus suscipit necessitatibus asperiores dolorum quae ex excepturi illum. Ratione ducimus, fugiat sit voluptates aliquid eveniet labore velit odio voluptas? Iste ullam tempore veniam. Molestiae adipisci assumenda, eius consequuntur aliquid, 
                                                    numquam dolore obcaecati, laboriosam minima repudiandae mollitia.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="manu">
                    <hr>
                        <h4>Manufacturers</h4>
                    <hr>
                    <div class="row damu">
                        {% if manufacturers %}
                            {% for items in manufacturers  %}
                                <div class="col-lg-2">
                                    <img src="{{items.manufacturers.url}}" alt="">
                                </div>
                            {% endfor %}
                        {% endif %}   
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="footer">
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="foot-hold">
                                <h6>Your Account</h6>
                                <ul>
                                    <li><a href="{% url 'user' %}"><span>YOUR ACCOUNT</span></a></li>
                                    <li><a href="{% url 'userupdate' %}"><span>PERSONAL INFORMATION</span></a></li>
                                    <li><a href=""><span>ADDRESSES</span></a></li>
                                    <li><a href=""><span>DISCOUNT</span></a></li>
                                    <li><a href=""><span>ORDER HISTORY</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="foot-hold">
                                <h6>Information</h6>
                                <ul>
                                    <li><a href="{% url 'contact' %}"><span>CONTACT</span></a></li>
                                    <li><a href=""><span>SITEMAP</span></a></li>
                                    <li><a href=""><span>LEGAL NOTICE</span></a></li>
                                    <li><a href=""><span>TERMS AND CONDITIONS</span></a></li>
                                    <li><a href=""><span>ABOUT US</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="foot-hold">
                                <h6>Our Offer</h6>
                                <ul>
                                    <li><a href=""><span>NEW PRODUCTS</span></a></li>
                                    <li><a href=""><span>TOP SELLERS</span></a></li>
                                    <li><a href=""><span>SPECIALS/span></a></li>
                                    <li><a href=""><span>MANUFACTURERS</span></a></li>
                                    <li><a href=""><span>SUPPLIERS</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="foot-hold foot-hold1">
                                <h6>{{profile.title|safe}}</h6>
                                <p>
                                    {{profile.about|safe}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}
</div>
<div class="container-fluid copyfoot1">
    {% block copyfoot %}{% endblock copyfoot %}
</div>