home/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('category/', views.category, name='category'),
    path('products/<str:id>/<slug:slug>', views.prod_list, name='prod_list'),
    path('products-details/<str:id>/<slug:slug>', views.prod_detail, name='prod_detail'),
]

order/urls.py
from django.urls import path
from . import views

app_name= 'order'

urlpatterns = [
    path('order/', views.order, name='order'),
    path('addtoshopcart/', views.addtoshopcart, name='addtoshopcart'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('updatequantity/', views.updatequantity, name='updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('ordercompleted/', views.ordercompleted, name='ordercompleted'),
]

shopa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as UserViews

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('login/', UserViews.loginform, name='loginform'),
    path('logout/', UserViews.logoutfunc, name='logoutfunc'),
    path('register/', UserViews.registerform, name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('update/', UserViews.userupdate, name='imageupdate'),
    path('password/', UserViews.userpassword, name='userpassword'),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from os import stat
from django.db import models
from django.contrib.auth.models import User

from django.forms import ModelForm
from product.models import *
from django.forms import Select

# Create your models here.


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(blank=True, null=False)
    color = models.CharField(max_length=10, blank=True, null=True)
    material = models.CharField(max_length=10, blank=True, null=True)
    order_code= models.CharField(max_length=70, editable=False)
    order_placed = models.BooleanField(default=False)

    def __str__(self):
        return self.product.title 
    
    @property
    def price(self):
        if self.product_id is not None:
            return (self.product.price)

    @property
    def amount(self):
        if self.product_id is  not None:
            return(None)
        else:
            if self.product.discount_price:
                return(self.product.discount_price * self.quantity)
            else:
                return(self.product.price * self.quantity)

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity', 'color',]  


class Order(models.Model):
    STATUS =(
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('Onshipping', 'Onshipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user= models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    total = models.FloatField(null=True, blank=True)
    order_placed = models.BooleanField(default=False)
    payment_code = models.CharField(max_length=70, editable=False)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, null=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    adminnote = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    
    


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']

order/views.py
from django.shortcuts import render,redirect

from django.http import HttpResponse

from django.contrib import messages
from home.models import *
from product.models import *
from .models import *
from user.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import requests
import json
import random
import string
import uuid
from django.views.decorators.http import require_POST

# Create your views here.


def order(request):
    return HttpResponse('e good')

@require_POST
@login_required(login_url='/login')
def addtoshopcart(request):
    url = request.META.get('HTTP_REFERER')
    thequantity = int(request.POST['quantity'])
    thecolor = request.POST.get('color', None)
    theprodid = request.POST['prodid']
    aprod = Product.objects.get(pk=theprodid)

    cart= ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)

    if cart: #an existing cart is noticed 
        prodchecker = ShopCart.objects.filter(product_id = aprod.id, color=thecolor, quantity=thequantity,user__username=request.user.username).first()

        if prodchecker: #product exists in the cart increment it
            prodchecker.quantity += thequantity
            prodchecker.color = thecolor
            prodchecker.save()
            messages.success(request, "Product added to Shopcart")
            return redirect(url)

        else: #product is not in cart add it
            anitem = ShopCart()
            anitem.product=aprod
            anitem.user=request.user
            anitem.order_code=cart[0].order_code
            anitem.quantity=thequantity
            anitem.color=thecolor
            anitem.order_placed=False
            anitem.save()
    
    else: #create a new cart,  generate order code
         ordercode = str(uuid.uuid4())
         newcart = ShopCart()
         newcart.product =aprod
         newcart.user =request.user
         newcart.order_code=ordercode
         newcart.quantity=thequantity
         newcart.color=thecolor 
         newcart.order_placed-False
         newcart.save()
    
    messages.success(request, "Product added to Shopcart")

    return redirect(url)



@login_required(login_url='/login')
def shopcart(request):

    profile= Profile.objects.get(pk=1)
    category = Category.objects.all()
    category_a = Category.objects.all()[:4]
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)
    profiles = UserProfile.objects.get(user__username = request.user.username)
    manufacturers = Manufacturers.objects.all()
    

    


    Subtotal=0
    Shippingfee=0
    vat=0
    total=0

    for item in shopcart:
        if item.product.discount_price:
            Subtotal += item.product.discount_price * item.quantity
        else:
            Subtotal += item.product_price *  item.quantity

    # Shipping rules: 8% fees to all orders above 450.0 fees to orders lower
    if Subtotal > 450:
        Shippingfee = 0.08 * Subtotal
    else:
        Shippingfee=0

    vat = 0.085 * Subtotal

    total = Subtotal + Shippingfee + vat

    context ={
        'profile': profile,
        'manufacturers': manufacturers,
        'profiles': profiles,
        'category': category,
        'category_a': category_a,
        'shopcart': shopcart,
        'Shipping': Shippingfee,
        'Subtotal': Subtotal,
        'vat': vat,
        'total': total,
        
    }
    
    return render(request,'shopcart.html', context)

@require_POST
@login_required(login_url='/login')
def updatequantity(request):
    url = request.META.get('HTTP_REFERER')
    newquantity = request.POST['itemquan']
    theitem = ShopCart.objects.get(id=request.POST ['itemid'])
    theitem.quantity = newquantity
    theitem.save()

    messages.success(request, "Product Quantity successfully updated")
    return redirect(url)

@login_required(login_url='/login')
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Item deleted from Shopcart.")
    return redirect('order:shopcart')



@login_required(login_url='/login')
def checkout(request):
    category = Category.objects.all()
    category_a = Category.objects.all()[:4]
    profile = Profile.objects.get(pk=1)
    shopcart = ShopCart.objects.filter(user__username = request.user.username).filter(order_placed=False)
    profiles = UserProfile.objects.get(user__username = request.user.username)
    manufacturers= Manufacturers.objects.all()

    Subtotal = 0
    Shippingfee = 0
    vat =0
    total = 0

    for item in shopcart:
        if item.product.discount_price:
            Subtotal += item.product.discount_price * item.quantity
        else:
            Subtotal += item.product.price * item.quantity

    # Shipping rules: 8% fees to all ordesa above 150.0. 0 fees nto orders lower
    if Subtotal > 150:
        Shippingfee = 0.08 * Subtotal
    else:
        Shippingfee = 0

    # vat is at 7.50% of the total purchase to be made
    vat = 0.075 * Subtotal

    total = Subtotal + Shippingfee + vat

    context = {
        'profile': profile,
        'manufacturers': manufacturers,
        'shopcart': shopcart,
        'order_code': shopcart[0].order_code,
        'profiles': profiles,
        'category': category,
        'category_a': category_a,
        'Subtotal': Subtotal,
        'Shipping': Shippingfee,
        'vat': vat,
        'total': total,
        
    }
    return render(request, 'checkout.html', context)



@require_POST
@login_required(login_url='/login')
def placeorder(request):
    api_key = 'sk_test_301780e41d9eca28ddbdeae67de0ea92ca974883'
    url = 'https://api.paystack.co/transaction/initialize'
    callback_url = 'http://3.17.204.0/order/ordercompleted/'
    ordercode = request.POST['order_number']
    autogen_ref = ''.join(random.choices(string.digits + string.ascii_letters, k=8))
    current_user = User.objects.get(username = request.user.username)
    user = UserProfile.objects.get(user_id = current_user.id)
    total = float(request.POST['amount']) * 100

    headers = {'Authorization': f'Bearer {api_key}'}
    data = {'reference': autogen_ref, 'amount': int(total), "currency": "NGN", 'order_number':ordercode, 'email':user.email, 'callback_url':callback_url}

    #making a request to PAYSTACK
    try:
        r=requests.post(url, headers=headers, json=data)
    except Exception:
        messages.error(request, "Network busy. Please try again in few minutes. Thank You")
    else:
        #create an order
        transback = json.loads(r.text)

        rd_url = transback['data']['authorization_url']
        theuser = UserProfile.objects.filter(user=request.user).first()
        order = Order()
        order.first_name=theuser.user.first_name
        order.last_name=theuser.user.last_name
        order.phone=theuser.phone
        order.city=theuser.city
        order.order_code=ordercode
        order.payment_code= autogen_ref
        order.total=total
        order.order_placed= True
        order.save()
        return redirect(rd_url)
    return redirect('order:checkout')



@login_required(login_url='/login')
def ordercompleted(request):
    category = Category.objects.all()
    profile = Profile.objects.get(pk=1)
    manufacturers= Manufacturers.objects.all()
    profiles = UserProfile.objects.get(user__username = request.user.username)
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username =request.user.username)

    #cleaning thr shopcart
    for item in shopcart:
        item.order_placed = True
        item.save()

        #reducing quantity in stock
        aproduct= Product.objects.get(id=item.product.id)
        aproduct.quantity_instock -= item.quantity
        aproduct.save()

    context ={
        'profile': profile,
        'category': category,
        'manufacturers': manufacturers,
        'shopcart': shopcart,
        'profiles': profiles,
    }      

    return render(request, 'ordercompleted.html', context)

order/templates/ordercompleted.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}


{% block ghead %}{% include "acheader.html" %}{% endblock ghead %}
<div class="container-fluid">
    {% block header %}{% include "header.html" %}{% endblock header %}
    {% block content %}
        <div class="container cpd dfd">
            <div class="catgo">
                <h6>ORDER COMPLETED</h6>
            </div>
        </div>
        <div class="container spd">
            <div class="order"> 
                <div class="order-hold">
                    <img src="{% static '' %}images/unnamed.png" alt="" width="200px" height="200px">
                </div>
                <div class="comword">
                    <h3><strong>Your Order is Complete!</strong></h3>
                    <p>You will be receiving a confimation email with order details.</p>
                </div>
                <div>
                    <a href="{% url 'index' %}"><span><i class="fa fa-repeat" aria-hidden="true"></i> Back to Homepage</span></a>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-12">
                    <div class="manu">
                        <hr>
                            <h4>Manufacturers</h4>
                        <hr>
                    <div class="row damu">
                        
                        {% if manufacturers %}
                            {% for items in manufacturers  %}
                                <div class="col-lg-2">
                                    <img src="{{items.manufacturers.url}}" alt="">
                                </div>
                            {% endfor %}
                        {% endif %}
                                
                    </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer">
                        <div class="row">
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Your Account</h6>
                                    <ul>
                                        <li><a href="{% url 'user' %}"><span>YOUR ACCOUNT</span></a></li>
                                        <li><a href="{% url 'userupdate' %}"><span>PERSONAL INFORMATION</span></a></li>
                                        <li><a href=""><span>ADDRESSES</span></a></li>
                                        <li><a href=""><span>DISCOUNT</span></a></li>
                                        <li><a href=""><span>ORDER HISTORY</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Information</h6>
                                    <ul>
                                        <li><a href="{% url 'contact' %}"><span>CONTACT</span></a></li>
                                        <li><a href=""><span>SITEMAP</span></a></li>
                                        <li><a href=""><span>LEGAL NOTICE</span></a></li>
                                        <li><a href=""><span>TERMS AND CONDITIONS</span></a></li>
                                        <li><a href=""><span>ABOUT US</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Our Offer</h6>
                                    <ul>
                                        <li><a href=""><span>NEW PRODUCTS</span></a></li>
                                        <li><a href=""><span>TOP SELLERS</span></a></li>
                                        <li><a href=""><span>SPECIALS/span></a></li>
                                        <li><a href=""><span>MANUFACTURERS</span></a></li>
                                        <li><a href=""><span>SUPPLIERS</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="foot-hold foot-hold1">
                                    <h6>{{profile.title|safe}}</h6>
                                    <p>
                                        {{profile.about|safe}}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endblock content %}
</div>
<div class="container-fluid copyfoot1">
    {% block copyfoot %}{% include "copyfoot.html" %}{% endblock copyfoot %}
</div>

order/templates/shopcart.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}


{% block ghead %}{% include "acheader.html" %}{% endblock ghead %}
<div class="container-fluid">
    {% block header %}{% include "header.html" %}{% endblock header %}
    {% block content %}
        <div class="container cpd dfd">
            <div class="catgo">
                <h6>SHOP CART</h6>
            </div>
        </div>
        <div class="container spd">
            <div class="row tabur">
                <div class="col-lg-12 tabu">
                    <div class="tab-hold">
                        <table class="table table-bordered">
                            <tr>
                                <th>IMAGE</th>
                                <th>PRODUCT</th>
                                <th>PRICE</th>
                                <th>COLOR</th>
                                <th>QUANTITY</th>
                                <th>TOTAL</th>
                            </tr>

                            
                            {% if shopcart %}
                                {% for items in shopcart  %}
                                    <tr>
                                        <td>
                                            <div class="cartimg">
                                                <img src="{{items.product.image.url}}" alt="">
                                            </div>
                                        </td>
                                        <td>
                                            <p style="font-weight: bold;">{{items.product.title}}</p>
                                        </td>
                                        <td>
                                            <p style="font-weight: bold;">
                                                {% if items.product.discount_price %}
                                                    {{items.product.discount_price | floatformat:2 | intcomma}}
                                                {% else %}
                                                    {{items.product.price | floatformat:2 | intcomma}}
                                                {% endif %}
                                            </p>
                                        </td>
                                        <td>
                                            <p style="font-weight: bold;">{{items.color}}</p>
                                        </td>
                                        <td>
                                            <div class="fleco">
                                                <a href="{% url 'order:deletefromcart' items.id %}">Remove </a>
                                                <form action="{% url 'order:updatequantity' %}" method="POST">
                                                {% csrf_token %}
                                                    <div>
                                                        <p style="font-weight: bold;"> <input type="number" id="items" name="itemquan" placeholder="Qty" style="width: 40px;" value="{{items.quantity}}" min="{{items.product.minquantity}}" max="{{items.product.quantity_instock}}"></p>
                                                    </div>
                                                    <div class="updateprice">
                                                        <button class="btu" type="submit">UPDATE QUANTITY</button>
                                                    </div>
                                                    <input type="hidden" name="itemid" value="{{items.id}}">
                                                </form>
                                                
                                            </div>
                                        </td>
                                        <td><p style="font-weight: bold;">{{items.total}}</p></td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                                
                        </table>
                    </div>
                    <div class="total-price">
                        <table>
                            <tr>
                                <td>Subtotal</td>
                                <td>&#8358; {{Subtotal | floatformat:2 | intcomma}}</td>
                            </tr>
                            <tr>
                                <td>Shipping Fee</td>
                                <td>&#8358; {{Shipping | floatformat:2 | intcomma}}</td>
                            </tr>
                            <tr>
                                <td>VAT (8.50%)</td>
                                <td>&#8358; {{vat | floatformat:2 | intcomma}}</td>
                            </tr>
                            <tr>
                                <td>Total</td>
                                <td>&#8358; {{total | floatformat:2 | intcomma}}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="tota-price">
                        <table>
                            <tr>
                                <td><button type="submit"><a href="{% url 'category' %}">Continue</a></button></td>
                                <td><button type="submit"><a href="{% url 'order:checkout' %}">Checkout</a></button></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="manu">
                        <hr>
                            <h4>Manufacturers</h4>
                        <hr>
                    <div class="row damu">
                        
                        {% if manufacturers %}
                            {% for items in manufacturers  %}
                        
                                <div class="col-lg-2">
                                    <img src="{{items.manufacturers.url}}" alt="">
                                </div>
                            {% endfor %}
                        {% endif %}
                                
                    </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer">
                        <div class="row">
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Your Account</h6>
                                    <ul>
                                        <li><a href="{% url 'user' %}"><span>YOUR ACCOUNT</span></a></li>
                                        <li><a href="{% url 'userupdate' %}"><span>PERSONAL INFORMATION</span></a></li>
                                        <li><a href=""><span>ADDRESSES</span></a></li>
                                        <li><a href=""><span>DISCOUNT</span></a></li>
                                        <li><a href=""><span>ORDER HISTORY</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Information</h6>
                                    <ul>
                                        <li><a href="{% url 'contact' %}"><span>CONTACT</span></a></li>
                                        <li><a href=""><span>SITEMAP</span></a></li>
                                        <li><a href=""><span>LEGAL NOTICE</span></a></li>
                                        <li><a href=""><span>TERMS AND CONDITIONS</span></a></li>
                                        <li><a href=""><span>ABOUT US</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="foot-hold">
                                    <h6>Our Offer</h6>
                                    <ul>
                                        <li><a href=""><span>NEW PRODUCTS</span></a></li>
                                        <li><a href=""><span>TOP SELLERS</span></a></li>
                                        <li><a href=""><span>SPECIALS/span></a></li>
                                        <li><a href=""><span>MANUFACTURERS</span></a></li>
                                        <li><a href=""><span>SUPPLIERS</span></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="foot-hold foot-hold1">
                                    <h6>{{profile.title|safe}}</h6>
                                    <p>
                                        {{profile.about|safe}}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</div>
<div class="container-fluid copyfoot1">
    {% block copyfoot %}{% include "copyfoot.html" %}{% endblock copyfoot %}
</div>